[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/search/:splat"
  status = 200
  force = true