[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"

[functions]
  directory = "backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200