[build]
  base = "/frontend"
  command = "npm run build"
  publish = "build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200