[build]
  command = "npm install && npm install --prefix frontend && npm install --prefix backend && npm run build --prefix frontend"
  publish = "frontend/build"
  functions = "backend"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200