[build]
  publish = "frontend/build"
  command = "npm run build --prefix frontend"

[functions]
  directory = "backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200