[build]
  base = "/frontend"
  publish = "build"
  command = "npm run build"

[context.production.environment]
  REACT_APP_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5001/:splat"
  status = 200
  force = true